name: aoc2018
version: 1.3.0.6

dependencies:
  - base
  - containers
  - criterion
  - parsec

library:
  exposed-modules:
    - Day1.Part1
    - Day1.Part2
  source-dirs: src

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -fno-warn-orphans
      - -fno-warn-unused-binds
      - -fno-warn-unused-imports
    dependencies:
      - aoc2018
      - hspec
