name: aoc2018
version: 1.3.0.6

dependencies:
  - base
  - array
  - containers
  - criterion
  - dlist
  - finite-typelits
  - linear
  - mtl
  - parallel
  - parsec
  - split
  - transformers
  - trifecta

library:
  exposed-modules:
    - Day1.Part1
    - Day1.Part2
    - Day2.Part1
    - Day2.Part2
    - Day3.Part1
    - Day3.Part2
    - Day4.Part1
    - Day4.Part2
    - Day5.Part1
    - Day5.Part2
    - Day6.Part1
    - Day6.Part2
    - Day7.Part1
    - Day7.Part2
    - Day8.Part1
    - Day8.Part2
    - Day9.Part1
    - Day9.Part2
    - Day10.Part1
    - Day10.Part2
    - Day11.Part1
    - Day11.Part2
    - Day12.Part1
    - Day12.Part2
    - Day13.Part1
    - Day13.Part2
  source-dirs: src

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -fno-warn-orphans
      - -fno-warn-unused-binds
      - -fno-warn-unused-imports
    dependencies:
      - aoc2018
      - hspec
