name: aoc2018
version: 1.3.0.6

dependencies:
  - base
  - containers
  - criterion
  - finite-typelits
  - parsec
  - split
  - trifecta

library:
  exposed-modules:
    - Day1.Part1
    - Day1.Part2
    - Day2.Part1
    - Day2.Part2
    - Day3.Part1
    - Day3.Part2
    - Day4.Part1
    - Day4.Part2
    - Day5.Part1
    - Day5.Part2
    - Day6.Part1
    - Day6.Part2
    - Day7.Part1
    - Day7.Part2
  source-dirs: src

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -fno-warn-orphans
      - -fno-warn-unused-binds
      - -fno-warn-unused-imports
    dependencies:
      - aoc2018
      - hspec
